export const INIT_MOVIES = 'INIT_MOVIES';
export const ADD_MOVIE = 'ADD_MOVIE';
export const REMOVE_MOVIE = 'REMOVE_MOVIE';
export const UPLOAD_MOVIE_ERROR = 'UPLOAD_MOVIE_ERROR"';
export const RESOLVE_UPLOAD_MOVIE_ERROR = 'RESOLVE_UPLOAD_MOVIE_ERROR';
