export const APP_RESOURCE_LOADING = 'APP_RESOURCE_LOADING';
export const APP_RESOURCE_LOADING_COMPLETE = 'APP_RESOURCE_LOADING_COMPLETE';

export const ADD_USER = 'ADD_USER';
export const REMOVE_CURRENT_USER = 'REMOVE_CURRENT_USER';

export const APP_MESSAGE = 'APP_MESSAGE';
export const RESOLVE_APP_MESSAGE = 'RESOLVE_APP_MESSAGE';

export const OPEN_APP_DIALOG = 'OPEN_APP_DIALOG';
export const CLOSE_APP_DIALOG = 'CLOSE_APP_DIALOG';
export const RESET_APP_DIALOG = 'RESET_APP_DIALOG';
